# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61a7fa91775c8ad92e12dde851943473"
name = "estimated-delivery-date"
application_url = "https://estimated-delivery-date.fly.dev"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[webhooks.privacy_compliance]
customer_data_request_url = "/webhooks/customers/data_request"
customer_deletion_url = "/webhooks/customers/redact"
shop_deletion_url = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"

[auth]
redirect_urls = [ "https://estimated-delivery-date.fly.dev/api/auth" ]

[app_proxy]
url = "/app-proxy"
prefix = "apps"
subpath = "estimated-delivery-date-app"
