# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61a7fa91775c8ad92e12dde851943473"
name = "estimated-delivery-date"
application_url = "https://estimated-delivery-date.fly.dev"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

# https://shopify.dev/docs/apps/build/compliance/privacy-law-compliance#subscribe-to-compliance-webhooks
[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "https://estimated-delivery-date.fly.dev/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"

[auth]
redirect_urls = [ "https://estimated-delivery-date.fly.dev/api/auth" ]

[app_proxy]
url = "/app-proxy"
prefix = "apps"
subpath = "estimated-delivery-date-app"
