# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61a7fa91775c8ad92e12dde851943473"
name = "estimated-delivery-date"
application_url = "https://estimated-delivery-date.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://estimated-delivery-date.fly.dev/api/auth" ]

[app_proxy]
url = "https://estimated-delivery-date.fly.dev"
subpath = "delivery"
prefix = "estimated-delivery-date-app"
